steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'GEMINI_API_KEY=$_GEMINI_API_KEY'
      - '--build-arg'
      - 'MAPS_API_KEY=$_MAPS_API_KEY'
      - '--build-arg'
      - 'FIREBASE_API_KEY=$_FIREBASE_API_KEY'
      - '--build-arg'
      - 'FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID'
      - '--build-arg'
      - 'FIREBASE_DATABASE_URL=$_FIREBASE_DATABASE_URL'
      - '-t'
      - 'us-central1-docker.pkg.dev/p2-o-fcb5d/cloud-run-source-deploy/aria-stadium-pro:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/p2-o-fcb5d/cloud-run-source-deploy/aria-stadium-pro:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'aria-stadium-pro'
      - '--image=us-central1-docker.pkg.dev/p2-o-fcb5d/cloud-run-source-deploy/aria-stadium-pro:latest'
      - '--region=us-central1'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/p2-o-fcb5d/cloud-run-source-deploy/aria-stadium-pro:latest'
